parameters:
  "service-dir":
    default: "sdk/fileshares"
emit:
  - "@azure-tools/typespec-autorest"
options:
  "@azure-tools/typespec-autorest":
    use-read-only-status-schema: true
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "resource-manager"
    output-file: "{version-status}/{version}/fileshares.json"
    arm-types-dir: "{project-root}/../../../../common-types/resource-management"
  "@azure-typespec/http-client-csharp-mgmt":
    namespace: "Azure.ResourceManager.FileShares"
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-mgmt-fileshares"
    namespace: "azure.mgmt.fileshares"
    generate-test: true
    generate-sample: true
    flavor: "azure"
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-resourcemanager-fileshares"
    namespace: "com.azure.resourcemanager.fileshares"
    service-name: "fileshares"
    flavor: azure
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/arm-fileshares"
    flavor: "azure"
    experimental-extensible-enums: true
    package-details:
      name: "@azure/arm-fileshares"
  "@azure-tools/typespec-go":
    service-dir: "sdk/resourcemanager/fileshares"
    emitter-output-dir: "{output-dir}/{service-dir}/armfileshares"
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/armfileshares"
    fix-const-stuttering: true
    flavor: "azure"
    generate-samples: true
    generate-fakes: true
    head-as-boolean: true
    inject-spans: true
  "@azure-tools/typespec-powershell":
    service-dir: "src"
    package-dir: "FileShare/FileShare.Autorest"
    clear-output-folder: true
    debug: true
    azure: true
    module-version: 0.1.0
    prefix: "Az"
    subject-prefix: "FileShare"
    service-name: FileShare
    module-name: "{prefix}.{service-name}"
    output-folder: "{output-dir}"
    exclude-tableview-properties:
      - Id
      - Type
    directive:
      - where:
          subject: Operation
        hide: true
      - where:
          parameter-name: SubscriptionId
        set:
          default:
            script: "(Get-AzContext).Subscription.Id"
      - where:
          variant: ^(Create|Update|Export)(?!.*?Expanded|ViaJsonString|ViaJsonFilePath)
        remove: true
      - where:
          variant: ^CreateViaIdentity$|^CreateViaIdentityExpanded$
        remove: true
      - where:
          verb: Set
        remove: true
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/resource-manager"
