parameters:
  "service-dir":
    default: "sdk/planetarycomputer"
  "dependencies":
    default: ""
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    azure-resource-provider-folder: "data-plane"
    emitter-output-dir: "{project-root}/.."
    output-file: "{azure-resource-provider-folder}/{service-name}/{version-status}/{version}/openapi.json"
    xml-strategy: none
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-planetarycomputer"
    namespace: "azure.planetarycomputer"
    generate-test: true
    generate-sample: true
    flavor: azure
  "@azure-typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    namespace: Azure.Analytics.PlanetaryComputer
    model-namespace: false
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/planetarycomputer"
    package-details:
      name: "@azure/planetarycomputer"
    flavor: azure
    is-modular-library: true
    experimental-extensible-enums: true
  "@azure-tools/typespec-java":
    package-dir: "azure-analytics-planetarycomputer"
    namespace: com.azure.analytics.planetarycomputer
    use-object-for-unknown: true
    flavor: azure
