parameters:
  "service-dir":
    default: "sdk/batch"
emit:
  - "@azure-tools/typespec-autorest"
linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"
options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}"
    output-file: "{version-status}/{version}/BatchService.json"
  "@azure-tools/typespec-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    clear-output-folder: true
    model-namespace: false
    head-as-boolean: false
    namespace: Azure.Compute.Batch
    flavor: azure
  "@azure-typespec/http-client-csharp":
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
    namespace: Azure.Compute.Batch
    model-namespace: false
  "@azure-tools/typespec-go":
    fix-const-stuttering: true
    generate-fakes: false
    inject-spans: true
    module: "github.com/Azure/azure-sdk-for-go/{service-dir}/azbatch"
    emitter-output-dir: "{output-dir}/{service-dir}/azbatch"
    service-dir: "sdk/batch"
    single-client: true
    slice-elements-byval: true
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-compute-batch"
    namespace: "com.azure.compute.batch"
    partial-update: true
    skip-special-headers:
      - "ocp-date"
    flavor: azure
    generate-tests: false
    generate-samples: false
    use-default-http-status-code-to-exception-type-mapping: false
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-batch"
    namespace: "azure.batch"
    flavor: azure
    generate-test: false
    generate-sample: false
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/batch"
    is-modular-library: true
    package-details:
      name: "@azure/batch"
      description: "Azure Batch client library for JavaScript"
      version: "13.0.0-beta.1"
    flavor: azure
