parameters:
  "service-dir":
    default: "sdk/monitor"
  "dependencies":
    default: ""

emit:
  - "@azure-tools/typespec-autorest"

linter:
  extends:
    - "@azure-tools/typespec-azure-rulesets/data-plane"

options:
  "@azure-tools/typespec-autorest":
    emitter-output-dir: "{project-root}"
    azure-resource-provider-folder: "data-plane"
    output-file: "preview/{version}/swagger.json"
    omit-unreachable-types: true
  "@azure-tools/typespec-python":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_generated"
    package-name: "azure-monitor-opentelemetry-exporter"
    flavor: azure
    namespace: "exporter"
    generate-packaging-files: false
    tracing: false
  "@azure-typespec/http-client-csharp":
    package-name: "Azure.Monitor.OpenTelemetry.Exporter"
    namespace: "{package-name}"
    model-namespace: false
    emitter-output-dir: "{output-dir}/{service-dir}/{namespace}"
  "@azure-tools/typespec-ts":
    emitter-output-dir: "{output-dir}/{service-dir}/monitor-opentelemetry-exporter"
    src-folder: "src/generated"
    generate-metadata: true
    is-modular-library: true
    package-details:
      name: "@azure/monitor-opentelemetry-exporter"
      description: "Azure Monitor OpenTelemetry Exporter"
    flavor: azure
    experimental-extensible-enums: true
  "@azure-tools/typespec-java":
    emitter-output-dir: "{output-dir}/{service-dir}/azure-monitor-opentelemetry-exporter"
    namespace: "com.azure.monitor.opentelemetry.exporter"
    flavor: azure
